Repository arborx/ArborX, pull requests merged in 2019-05, with the labels that each got.

#25 Fix unused variable warnings
  src/details/ArborX_DetailsTreeVisualization.hpp
  test/ArborX_BoostRTreeHelpers.hpp
Labels: build

#27 Find kokkos module
  CMakeLists.txt
  cmake/FindKokkos.cmake
  docker/Dockerfile
  docker/kokkos.patch
  test/CMakeLists.txt
Labels: build

#31 Provide an option to disable tests and examples
  CMakeLists.txt
Labels: build

#35 Fix Kokkos_DEVICES spelling
  CMakeLists.txt
Labels: bug, build

#21 Export CMake config
  CMakeLists.txt
  cmake/ArborXConfig.cmake.in
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: build

#24 Relax CudaUVM requirement
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/CMakeLists.txt
  test/headers_self_contained/tstHeader.cpp
  test/tstLinearBVH.cpp
Labels: build

#11 Add Kokkos profiling regions
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
Labels: performance
