Repository arborx/ArborX, pull requests merged in 2019-10, with the labels that each got.

#134 Optimize communication within the same rank
  src/details/ArborX_DetailsDistributor.hpp
Labels: bug

#135 Use MPI_Comm_dup to separate ArborX comm context from user's
  src/ArborX_DistributedSearchTree.hpp
Labels: enhancement

#129 Fix for distributed searches with large count of results per que…
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  test/tstDistributedSearchTree.cpp
Labels: bug

#151 Update README with links to build and API
  README.md
Labels: documentation

#156 Use with Trilinos' Kokkos installation
  cmake/FindKokkos.cmake
  docs/build.md
Labels: documentation, enhancement

#107 Add access traits CUDA example
  docs/traits.md
  examples/CMakeLists.txt
  examples/access_traits/CMakeLists.txt
  examples/access_traits/example_cuda_access_traits.cpp
Labels: enhancement

#147 Use Thrust for GPU sort
  src/details/ArborX_DetailsSortUtils.hpp
Labels: performance

#164 Add timeout to CI step that runs the unit tests
  .jenkins
Labels: testing

#162 CUDA-aware MPI
  CMakeLists.txt
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  cmake/ArborXSettings.cmake.in
  src/ArborX_Config.hpp.in
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
Labels: performance

#137 Add PGI in .jenkins
  .jenkins
  docker/Dockerfile.pgi
Labels: build

#181 Enable compiler warnings in the CI
  .jenkins
  src/details/ArborX_DetailsTreeVisualization.hpp
Labels: testing
