Repository arborx/ArborX, pull requests merged in 2019-11, with the labels that each got.

#184 Fix header_self_contained test and including ArborX_Config.hpp
  CMakeLists.txt
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  test/headers_self_contained/CMakeLists.txt
  test/headers_self_contained/tstHeader.cpp
Labels: bug

#170 Trigger build from comment on the pull request
  .jenkins
Labels: testing

#172 Parallelize sortAndDetermineBufferLayout
  src/details/ArborX_DetailsDistributor.hpp
Labels: performance

#189 Use sortObjects in sortResults.
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsSortUtils.hpp
Labels: performance

#195 Disable errors on warnings until figure it out
  .jenkins
Labels: testing

#193 Keep permutation on the device
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
Labels: performance
