Repository arborx/ArborX, pull requests merged in 2020-06, with the labels that each got.

#290 Add batch mode to bvh on-node driver
  .gitlab-ci.yml
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/point_clouds/point_clouds.hpp
Labels: enhancement

#337 Remove no header
  .gitlab-ci.yml
  benchmarks/bvh_driver/bvh_driver.cpp
Labels: testing

#300 Propose Traits::Access -> AccessTraits
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/access_traits/example_host_access_traits.cpp
  examples/callback/example_callback.cpp
  src/ArborX_DistributedSearchTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsBufferOptimization.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  test/tstAccessTraits.cpp
  test/tstCallbacks.cpp
  test/tstDetailsBufferOptimization.cpp
Labels: API
