Repository arborx/ArborX, pull requests merged in 2020-10, with the labels that each got.

#364 Implement stackless tree traversal using escape index (ropes)
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement, performance

#408 Temporary workaround for failures in HIP CI build
  test/tstLinearBVH.cpp
Labels: testing

#331 Implement DBSCAN
  examples/CMakeLists.txt
  examples/dbscan/ArborX_DBSCAN.hpp
  examples/dbscan/ArborX_DetailsDBSCANCallback.hpp
  examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
  examples/dbscan/CMakeLists.txt
  examples/dbscan/LICENSE.ECL
  examples/dbscan/README.md
  examples/dbscan/dbscan.cpp
  examples/dbscan/input.txt
  examples/halo_finder/ArborX_HaloFinder.hpp
  examples/halo_finder/CMakeLists.txt
  examples/halo_finder/README.md
Labels: application, enhancement

#418 Use ropes on AMD GPUs as well
  src/ArborX_LinearBVH.hpp
Labels: performance

#412 Add testing of new query overload to the perf benchmark
  .gitlab-ci.yml
  benchmarks/bvh_driver/bvh_driver.cpp
  test/ArborX_BoostRTreeHelpers.hpp
Labels: testing
