Repository arborx/ArborX, pull requests merged in 2020-08, with the labels that each got.

#329 New BVH::query() overload that only takes predicates and callback
  examples/callback/example_callback.cpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsBufferOptimization.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_Predicates.hpp
  test/tstDetailsBufferOptimization.cpp
Labels: API

#351 Do not build host access traits when Cuda is enabled
  examples/access_traits/CMakeLists.txt
Labels: build

#241 Fix scaling issues in the distributed driver for 1D and 2D
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
Labels: bug

#356 Add new query overloads for the distributed tree
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/CompressedSparseRow.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedSearchTree.cpp
  test/tstLinearBVH.cpp
  test/tstMiscellaneous.cpp
Labels: API

#360 Resolve duplicate Details::toBufferStatus(int) symbol error downstream
  src/details/ArborX_DetailsBufferOptimization.hpp
Labels: bug

#357 Improve performance of knn traversal
  src/details/ArborX_DetailsTreeTraversal.hpp
Labels: performance

#361 Remove deprecated nearest traversals
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
Labels: refactoring

#350 Apetrei's construction algorithm
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsKokkosExt.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: performance

#365 Add MPI guards for test helpers
  .jenkins
  test/Search_UnitTestHelpers.hpp
Labels: bug, testing
