Repository arborx/ArborX, pull requests merged in 2020-09, with the labels that each got.

#379 Run Style check before Builds
  .jenkins
Labels: testing

#380 Ensure that all kernels from BVH are properly marked
  test/CMakeLists.txt
  test/VectorOfTuples.hpp
  test/tstKokkosToolsAnnotations.cpp
Labels: API, testing

#371 Apply clang-tidy also to header files
  .clang-tidy
  examples/halo_finder/ArborX_HaloFinder.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsPriorityQueue.hpp
  src/details/ArborX_DetailsUtils.hpp
  test/ArborX_BoostGeometryAdapters.hpp
  test/ArborX_BoostRangeAdapters.hpp
Labels: testing

#382 GPU isolation on CI builds
  .jenkins
Labels: testing

#381 Prefix view names allocated from BVH
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBufferOptimization.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstKokkosToolsAnnotations.cpp
Labels: API, testing

#396 Deprecate DistributedSearchTree
  benchmarks/distributed_tree_driver/CMakeLists.txt
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/ArborX.hpp
  src/ArborX_DistributedSearchTree.hpp
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/tstDetailsDistributedTreeImpl.cpp
  test/tstDistributedTree.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
Labels: API

#395 Initialize leaf nodes in hierarchy generation
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: refactoring

#400 Ignore #pragma-messages warnings in CI
  .jenkins
Labels: testing

#392 Update HIP CI to version 3.8
  .jenkins
  docker/Dockerfile.hipcc
Labels: testing
