Repository arborx/ArborX, pull requests merged in 2020-03, with the labels that each got.

#155 Store indices of children nodes rather than pointer in the bounding volume hierarchy
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement

#240 Buffer optimization fix for empty results
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
Labels: performance

#223 Build PGI image live
  .jenkins
  docker/Dockerfile.pgi
Labels: testing

#235 Use single precision floating point numbers for coordinates
  src/details/ArborX_Box.hpp
  src/details/ArborX_DetailsAlgorithms.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsKokkosExt.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_Point.hpp
  src/details/ArborX_Sphere.hpp
  test/ArborX_BoostGeometryAdapters.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstBoostGeometryAdapters.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDistributedSearchTree.cpp
  test/tstLinearBVH.cpp
Labels: performance

#243 Optional sorting of predicates
  benchmarks/bvh_driver/bvh_driver.cpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  test/tstLinearBVH.cpp
Labels: API, enhancement, performance

#249 Drop extra parallel_reduce() when sorting objects in distributed tree
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Labels: performance

#253 Fix reference in documentation
  docs/bounding_volume_hierarchy.md
  docs/traits.md
Labels: documentation
