Repository arborx/ArborX, pull requests merged in 2020-04, with the labels that each got.

#56 Logo
  .gitattributes
  README.md
  docs/logos/arborx_logo_v1.0.png
  docs/logos/arborx_logo_v1.0.svg
  docs/logos/arborx_logo_v1.0_nobg.png
Labels: documentation

#200 Allow queries in benchmark to differ from local points
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
Labels: enhancement, performance, testing

#257 Remove a few unnecessary view initialization in distributed search tree internals
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Labels: performance

#258 Get rid of one stray view initialization in forwardQueries()
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
Labels: performance

#246 Do not specify keyserver for LLVM key
  docker/Dockerfile
Labels: testing

#262 Update Boost installation process in Docker images
  docker/Dockerfile
  docker/Dockerfile.pgi
Labels: testing

#267 Fixup Details::sortObject() overload for Cuda execution space
  src/details/ArborX_DetailsSortUtils.hpp
Labels: performance

#234 Remove no longer necessary Trilinos-specific code to allow building against Trilinos installation of Kokkos
  CMakeLists.txt
  cmake/FindKokkos.cmake
  test/CMakeLists.txt
Labels: build

#274 Fixup document nearest(..., k=1) default argument
  docs/predicates.md
Labels: documentation

#268 Kokkos 3.1
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.pgi
  docs/build.md
  src/ArborX_DistributedSearchTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Box.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsContainers.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsPriorityQueue.hpp
  src/details/ArborX_DetailsStack.hpp
  src/details/ArborX_Point.hpp
  src/details/ArborX_Predicates.hpp
  src/details/ArborX_Sphere.hpp
Labels: build, documentation, testing

#242 Use unsigned int for permutation indices instead of size_t
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: performance

#280 Use scope guards in the documentation and examples
  docs/bounding_volume_hierarchy.md
  docs/traits.md
Labels: documentation

#284 Disable tests, examples, benchmarks by default
  .jenkins
  CMakeLists.txt
Labels: build, testing

#286 Require boost < 1.69 for CUDA-enabled tests
  test/CMakeLists.txt
Labels: testing

#277 Update check_format_cpp.sh script
  .clang-format-ignore
  scripts/check_format_cpp.sh
Labels: enhancement

#283 Update build and install documentation
  docs/build.md
Labels: documentation

#289 Fix radius calculation for on-node benchmark
  benchmarks/bvh_driver/bvh_driver.cpp
Labels: bug

#222 Always permute on the device
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsSortUtils.hpp
Labels: performance

#285 Properly clear out boost directory when building Docker image
  docker/Dockerfile
  docker/Dockerfile.pgi
Labels: testing

#288 Use Clang workaround for Thrust regarless of the version
  src/details/ArborX_DetailsSortUtils.hpp
Labels: bug, build
