Repository arborx/ArborX, pull requests merged in 2020-02, with the labels that each got.

#166 Enable user-defined callback in BVH search
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsConcepts.hpp
  src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_Predicates.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/Search_UnitTestHelpers.hpp
  test/boost_ext/KokkosPairComparison.hpp
  test/tstDistributedSearchTree.cpp
  test/tstLinearBVH.cpp
Labels: enhancement

#219 Fix node parsing in the distributed benchmark
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
Labels: bug

#207 Allow valid JSON output from benchmark
  benchmarks/bvh_driver/bvh_driver.cpp
Labels: enhancement

#93 Require Kokkos CMake build
  .jenkins
  CMakeLists.txt
  cmake/FindKokkos.cmake
  docker/Dockerfile
  docker/Dockerfile.pgi
  examples/access_traits/CMakeLists.txt
  examples/viz/CMakeLists.txt
  test/CMakeLists.txt
Labels: build

#227 Update Kokkos required version in docs
  docs/build.md
Labels: documentation

#55 Fix Jenkins CI test logs
  .jenkins
  docker/Dockerfile
Labels: testing

#228 Update PGI build to display all warnings and test installation
  .jenkins
Labels: testing

#229 Enable skipping the build on Jenkins
  .jenkins
Labels: testing
