Repository arborx/ArborX, pull requests merged in 2020-05, with the labels that each got.

#287 Retain the original path to Kokkos
  cmake/ArborXConfig.cmake.in
Labels: build

#296 Update testing framework
  .jenkins
  docker/Dockerfile
  docker/Dockerfile.pgi
  src/details/ArborX_DetailsDistributor.hpp
Labels: bug, testing

#297 Address clang-tidy-10 warnings
  .clang-tidy
  .jenkins
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  test/tstLinearBVH.cpp
Labels: testing

#302 Remove orphaned documentation (migrated to wiki)
  README.md
  docs/bounding_volume_hierarchy.md
  docs/build.md
  docs/predicates.md
  docs/traits.md
Labels: documentation

#304 Use specific directory for ArborX install in PGI and Clang builds
  .jenkins
Labels: testing

#237 Halo finder
  examples/CMakeLists.txt
  examples/halo_finder/ArborX_HaloFinder.hpp
  examples/halo_finder/CMakeLists.txt
  examples/halo_finder/LICENSE.ECL
  examples/halo_finder/README.md
  examples/halo_finder/halo_finder.cpp
  examples/halo_finder/input.txt
Labels: application

#282 Complete buffer optimization refactoring
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsBufferOptimization.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  test/CMakeLists.txt
  test/tstDetailsBatchedQueries.cpp
  test/tstDetailsBufferOptimization.cpp
  test/tstLinearBVH.cpp
Labels: enhancement, refactoring

#306 Workaround for Stack performance
  src/details/ArborX_DetailsTreeTraversal.hpp
  test/tstLinearBVH.cpp
Labels: performance

#307 Enable building and testing against Kokkos with pthread enabled
  .jenkins
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  test/CMakeLists.txt
Labels: testing

#310 Drop QUIET option when finding Kokkos
  CMakeLists.txt
Labels: build

#312 Do not build benchmark tests when building container
  docker/Dockerfile
  docker/Dockerfile.pgi
Labels: testing

#276 Measure performance regression
  .github/workflows/gitlab-ci.yml
  .gitlab-ci.yml
  benchmarks/bvh_driver/CMakeLists.txt
  benchmarks/bvh_driver/bvh_driver.cpp
Labels: testing

#309 Better support for comparing compressed storage in unit tests
  test/boost_ext/CompressedStorageComparison.hpp
  test/tstLinearBVH.cpp
Labels: testing

#308 Switch knn to the same stack approach as radius Karras
  src/details/ArborX_DetailsTreeTraversal.hpp
Labels: performance

#316 This attempt did not go well, github was simply down
  .github/workflows/gitlab-ci-copy.yml
Labels: testing

#320 Cleanup Boost RTree comparisons in unit tests
  benchmarks/bvh_driver/bvh_driver.cpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/tstLinearBVH.cpp
Labels: testing

#326 Let BVH::bounds() be a KOKKOS_FUNCTION
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
Labels: API

#325 Add example for callbacks and lift requirement for tagging inline
  examples/CMakeLists.txt
  examples/callback/CMakeLists.txt
  examples/callback/example_callback.cpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  test/tstCallbacks.cpp
Labels: API, documentation, enhancement
