Repository arborx/ArborX, pull requests merged in 2020-12, with the labels that each got.

#424 Use rocThrust to sort instead of Kokkos native capability
  .jenkins
  CMakeLists.txt
  cmake/ArborXConfig.cmake.in
  cmake/ArborXSettings.cmake.in
  docker/Dockerfile.hipcc
  src/ArborX_Config.hpp.in
  src/details/ArborX_DetailsSortUtils.hpp
Labels: performance

#426 Stop using BVH<DeviceType> and DistributedTree<DeviceType> internally
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedTree.cpp
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
  test/tstLinearBVH.cpp
Labels: testing

#428 Terminate DBSCAN's neighbor counting early once threshold is reached
  examples/dbscan/ArborX_DBSCAN.hpp
Labels: performance

#431 Fix using of uninitialized value in DBSCAN timer
  examples/dbscan/ArborX_DBSCAN.hpp
Labels: bug

#430 Speed up DBSCAN post-processing
  examples/dbscan/ArborX_DBSCAN.hpp
Labels: performance

#436 Fix ambiguities arising from using initializer lists without specifying a type
  src/details/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: testing

#366 Change signature of the nearest callback
  benchmarks/bvh_driver/bvh_driver.cpp
  examples/callback/example_callback.cpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsBufferOptimization.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstCallbacks.cpp
  test/tstDetailsBufferOptimization.cpp
  test/tstDistributedTree.cpp
  test/tstLinearBVH.cpp
Labels: API

#440 Fix performance regression introduced in #366
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
Labels: performance

#423 Add CI for SYCL
  .jenkins
  benchmarks/bvh_driver/bvh_driver.cpp
  docker/Dockerfile.sycl
  examples/callback/example_callback.cpp
  examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: testing

#439 Use Kokkos built-in reducer in bounding scene calculation
  src/details/ArborX_Box.hpp
  src/details/ArborX_DetailsAlgorithms.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: build

#441 Fixup builtin reducer type requirements for SYCL backend
  src/details/ArborX_Box.hpp
Labels: build

#425 Externalize crs graph
  benchmarks/bvh_driver/bvh_driver.cpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/callback/example_callback.cpp
  examples/dbscan/ArborX_DBSCAN.hpp
  src/ArborX.hpp
  src/ArborX_CrsGraphWrapper.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsPermutedData.hpp
  src/details/ArborX_TraversalPolicy.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
  test/tstLinearBVH.cpp
Labels: refactoring

#443 Drop (unused) vector of tuples unit test utility
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/VectorOfTuples.hpp
  test/tstMiscellaneous.cpp
Labels: testing

#447 Update ROCm to 4.0
  .jenkins
  docker/Dockerfile.hipcc
  test/tstLinearBVH.cpp
Labels: testing
