Repository arborx/ArborX, pull requests merged in 2021-02, with the labels that each got.

#472 Clarify bounding volume and predicate geometry type requirements
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_Predicates.hpp
  test/CMakeLists.txt
  test/tstDetailsTypeRequirements.cpp
Labels: API

#471 Restore expected failures decorators for HIP
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeManufacturedSolution.cpp
Labels: testing

#473 Avoid unnecessary rebuilds for generated unit test source files
  test/CMakeLists.txt
Labels: build, testing

#410 Add plotting script for benchmark
  scripts/benchmark.py
  scripts/benchmark_plot.py
  scripts/requirements.txt
Labels: enhancement

#476 Merge all compile-only unit tests into a single executable
  test/CMakeLists.txt
  test/tstCompileOnlyAccessTraits.cpp
  test/tstCompileOnlyCallbacks.cpp
  test/tstCompileOnlyConcepts.cpp
  test/tstCompileOnlyMain.cpp
  test/tstCompileOnlyTypeRequirements.cpp
Labels: build, testing

#479 Avoid cluttering the console log in annotations tests
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
Labels: testing

#480 Consolidate all geometry unit test into a single executable
  test/CMakeLists.txt
  test/tstDetailsAlgorithms.cpp
  test/tstRay.cpp
Labels: refactoring, testing

#481 Add option to disable header self containment tests
  CMakeLists.txt
  test/CMakeLists.txt
Labels: testing

#483 Cleanup query tree unit tests
  test/ArborXTest_TreeTypeTraits.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeManufacturedSolution.cpp
  test/tstQueryTreeTraversalPolicy.cpp
Labels: testing

#470 Reorganize benchmark directory
  benchmarks/bvh_driver/benchmark_registration.hpp
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/point_clouds/point_clouds.hpp
Labels: refactoring

#478 Change API and reorganize DBSCAN structure
  examples/dbscan/ArborX_DBSCAN.hpp
  examples/dbscan/ArborX_DetailsDBSCANCallback.hpp
  examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
  examples/dbscan/dbscan.cpp
Labels: API
