Repository arborx/ArborX, pull requests merged in 2021-05, with the labels that each got.

#506 Create new UnionFind struct for DBSCAN
  src/details/ArborX_DetailsDBSCANCallback.hpp
  src/details/ArborX_DetailsUnionFind.hpp
Labels: clustering, refactoring

#512 Fix warnings from hipcc
  src/details/ArborX_DetailsDBSCANCallback.hpp
  src/details/ArborX_DetailsUnionFind.hpp
Labels: build

#502 Let abstraction for Euclidean vector be strongly typed
  examples/raytracing/example_raytracing.cpp
  src/details/ArborX_Ray.hpp
  test/tstRay.cpp
Labels: refactoring

#518 Fix build error when using Vector inside Ray
  src/details/ArborX_Ray.hpp
Labels: build

#519 Rename DBSCANCallback to FDBSCANCallback
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
Labels: refactoring

#522 Add support for MI 100 in CI
  .jenkins
  docker/Dockerfile.hipcc
Labels: testing

#521 Add and install ArborXConfigVersion.cmake
  CMakeLists.txt
  examples/CMakeLists.txt
Labels: build

#499 Update CI to ROCm 4.2
  .jenkins
  docker/Dockerfile.hipcc
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeManufacturedSolution.cpp
Labels: testing

#386 Add polytope to explore using it as bounding volume
  src/details/ArborX_KDOP.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/CMakeLists.txt
  test/tstKDOP.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeIntersectsKDOP.cpp
  test/tstQueryTreeManufacturedSolution.cpp
Labels: enhancement

#456 Use oneDPL for sorting with SYCL
  .jenkins
  CMakeLists.txt
  cmake/ArborXConfig.cmake.in
  cmake/ArborXSettings.cmake.in
  docker/Dockerfile.sycl
  src/ArborX_Config.hpp.in
  src/details/ArborX_DetailsSortUtils.hpp
  test/tstDetailsUtils.cpp
Labels: performance, testing

#524 Remove unnecessary variable in HIP Dockerfile
  docker/Dockerfile.hipcc
Labels: testing

#525 Fix a subtle bug in DBSCAN noise marking
  examples/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_DBSCAN.hpp
  test/tstDBSCAN.cpp
Labels: bug, clustering

#527 Rename "boundary" to "border" in DBSCAN
  examples/dbscan/ArborX_DBSCANVerification.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
  test/tstHeapOperations.cpp
Labels: clustering

#508 Introduce new algorithm (FDBSCAN-DenseBox) for DBSCAN
  examples/dbscan/ArborX_DBSCANVerification.hpp
  examples/dbscan/dbscan.cpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  test/tstDBSCAN.cpp
Labels: clustering, performance, refactoring

#526 Reduce default value of cluster_min_size in DBSCAN to 1
  examples/dbscan/dbscan.cpp
Labels: clustering

#529 Change default DBSCAN implementation to FDBSCAN-DenseBox
  src/ArborX_DBSCAN.hpp
Labels: API, clustering
