Repository arborx/ArborX, pull requests merged in 2021-01, with the labels that each got.

#451 Reorganize query tree unit tests
  test/ArborXTest_TreeTypeTraits.hpp
  test/CMakeLists.txt
  test/tstLinearBVH.cpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeManufacturedSolution.cpp
  test/tstQueryTreeTraversalPolicy.cpp
Labels: testing

#450 Fence ArborX calls in the benchmark and (optionally) DBSCAN
  benchmarks/bvh_driver/bvh_driver.cpp
  examples/dbscan/ArborX_DBSCAN.hpp
Labels: testing

#453 Update DBSCAN post-processing to avoid calling sort
  examples/dbscan/ArborX_DBSCAN.hpp
  examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
  examples/dbscan/dbscan.cpp
  src/details/ArborX_DetailsHeap.hpp
  test/tstHeapOperations.cpp
Labels: performance

#458 Introduce BasicBoundingVolumeHierarchy<MemorySpace, BoundingVolume>
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: refactoring

#467 Drop unused type traits
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsConcepts.hpp
  test/tstDetailsConcepts.cpp
Labels: refactoring

#465 Breakout KokkosExt header and partial cleanup of includes
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Box.hpp
  src/details/ArborX_DetailsAlgorithms.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsKokkosExtAccessibilityTraits.hpp
  src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp
  src/details/ArborX_DetailsKokkosExtMathFunctions.hpp
  src/details/ArborX_DetailsKokkosExtMinMaxOperations.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_Ray.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/ArborX_EnableViewComparison.hpp
  test/Search_UnitTestHelpers.hpp
Labels: refactoring

#466 Move comparison function objects out of priority queue header
  examples/dbscan/dbscan.cpp
  src/details/ArborX_DetailsOperatorFunctionObjects.hpp
  src/details/ArborX_DetailsPriorityQueue.hpp
Labels: refactoring

#459 Query tree unit test (partial) cleanup
  test/CMakeLists.txt
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeManufacturedSolution.cpp
Labels: refactoring, testing

#469 Align the meaning of min_pts parameter in DBSCAN with literature
  examples/dbscan/ArborX_DBSCAN.hpp
  examples/dbscan/ArborX_DetailsDBSCANVerification.hpp
  examples/dbscan/dbscan.cpp
Labels: API

#468 Add BruteForce data structure
  src/ArborX_BruteForce.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
Labels: enhancement
