Repository arborx/ArborX, pull requests merged in 2021-12, with the labels that each got.

#575 Return getBoundingVolume by value to work around HIP optimizer
  src/details/ArborX_DetailsHappyTreeFriends.hpp
Labels: performance

#579 Bugfix bounding volume accesses in generate hierarchy
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: bug, performance

#583 Rename `{ArborX::Details:: -> KokkosExt::}[is_]detected`
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsKokkosExtDetectionIdiom.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyConcepts.cpp
Labels: refactoring

#588 Remove `<ArborX_DetailsTags.hpp>`
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsTags.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: refactoring

#589 Silence warning in SYCL backend for unknown CUDA version in installed version
  .jenkins/continuous.groovy
Labels: testing

#590 Remove PGI build from CI
  .jenkins/continuous.groovy
  docker/Dockerfile.pgi
Labels: testing

#584 Add intersects(Sphere, Point) and intersects(Point, Sphere)
  src/details/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#578 Require minimum of Kokkos version 3.4
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.hipcc
  docker/README.md
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
  test/tstScopedProfileRegion.cpp
Labels: build, testing

#592 Fixup `Kokkos_ENABLE_PTHREAD` is being deprecated
  test/CMakeLists.txt
Labels: build

#593 Do not use `Kokkos::Impl::min_max_functor`
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsUtils.hpp
Labels: refactoring

#576 Fix an issue in the query test using manufactured solution
  test/tstQueryTreeManufacturedSolution.cpp
Labels: testing

#597 Use CUDA-aware MPI in DistributedTree constructor
  src/ArborX_DistributedTree.hpp
Labels: enhancement, performance

#596 Introduce helper functions for label reduction on a hierarchy
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsTreeNodeLabeling.hpp
  test/CMakeLists.txt
  test/tstDetailsTreeNodeLabeling.cpp
Labels: enhancement

#601 use different master branch on GitLab CI
  .gitlab-ci.yml
Labels: testing

#603 Fix link to examples directory
  README.md
Labels: documentation

#600 Add functionality to compute mutual reachability distances
  src/details/ArborX_DetailsKokkosExtMinMaxOperations.hpp
  src/details/ArborX_DetailsMutualReachabilityDistance.hpp
  test/ArborXTest_StdVectorToKokkosView.hpp
  test/CMakeLists.txt
  test/tstDetailsMutualReachabilityDistance.cpp
  test/tstDetailsTreeNodeLabeling.cpp
Labels: enhancement
