Repository arborx/ArborX, pull requests merged in 2021-11, with the labels that each got.

#567 Rename jenkinsfile
  .jenkins/continuous.groovy
Labels: testing

#566 Fix exit status of the dbscan example
  examples/dbscan/dbscan.cpp
Labels: bug

#568 [ci skip] Update DBSCAN README
  examples/dbscan/README.md
Labels: documentation

#569 Add Jenkinsfile for nightly builds
  .jenkins/nightly.groovy
Labels: testing

#570 Fixup run benchmarks in the nightly build
  .jenkins/nightly.groovy
Labels: testing

#571 Ignore cv qualifiers in arithmetic traits
  src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp
Labels: refactoring

#572 Cleanup `Experimental::Ray`
  src/details/ArborX_Ray.hpp
Labels: refactoring

#564 Add molecular dynamics example
  examples/CMakeLists.txt
  examples/molecular_dynamics/CMakeLists.txt
  examples/molecular_dynamics/example_molecular_dynamics.cpp
Labels: enhancement

#573 Refactor ray-box and ray-sphere intersection algorithms
  src/details/ArborX_DetailsKokkosExtSwap.hpp
  src/details/ArborX_Ray.hpp
  test/tstRay.cpp
Labels: enhancement, refactoring
