Repository arborx/ArborX, pull requests merged in 2021-04, with the labels that each got.

#504 Reduce default problem size for the distributed benchmark
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
Labels: testing

#503 Reorganize DBSCAN location and add unit testing
  docs/LICENSE.ECL
  examples/dbscan/ArborX_DBSCANVerification.hpp
  examples/dbscan/CMakeLists.txt
  examples/dbscan/dbscan.cpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsDBSCANCallback.hpp
  test/CMakeLists.txt
  test/tstDBSCAN.cpp
Labels: refactoring, testing

#505 Remove "fast" label initialization
  src/details/ArborX_DetailsDBSCANCallback.hpp
Labels: clustering

#491 Add data converters for DBSCAN
  examples/dbscan/CMakeLists.txt
  examples/dbscan/converter.cpp
  examples/dbscan/dbscan.cpp
Labels: clustering

#500 Use Attorney-Client idiom for BVH
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
Labels: refactoring

#510 Fix clang-tidy warnings in the converter
  examples/dbscan/converter.cpp
Labels: build

#509 Use AccessTraits instead of hardcoded View in DBSCAN
  examples/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_DBSCAN.hpp
  test/tstDBSCAN.cpp
Labels: clustering

#511 Use Kokkos 3.4 for SYCL
  docker/Dockerfile.sycl
Labels: testing
