Repository arborx/ArborX, pull requests merged in 2021-03, with the labels that each got.

#486 Require CMake 3.16
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.pgi
Labels: build

#487 Update SYCL in CI to fix building the compiler
  docker/Dockerfile.sycl
Labels: testing

#489 Cleanup miscellaneous priority queue unit test
  test/CMakeLists.txt
  test/tstContainerAdaptors.cpp
  test/tstPriorityQueueMiscellaneous.cpp
  test/tstSequenceContainers.cpp
Labels: refactoring, testing

#332 Attempt using the latest Boost release with NVCC
  docker/Dockerfile
  test/CMakeLists.txt
Labels: build

#494 Add Box-Box distance for Nearest query
  src/details/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
Labels: enhancement

#495 Compute distance sphere-box
  src/details/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement
