Repository arborx/ArborX, pull requests merged in 2021-09, with the labels that each got.

#513 Add simple intersection example
  README.md
  examples/CMakeLists.txt
  examples/simple_intersection/CMakeLists.txt
  examples/simple_intersection/example_intersection.cpp
Labels: documentation, testing

#546 Fix DBSCAN test input file
  examples/dbscan/input.txt
Labels: bug

#548 Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation
