Repository arborx/ArborX, pull requests merged in 2022-08, with the labels that each got.

#709 Don't search for oneDPL if the compiler already provides it
  CMakeLists.txt
  cmake/ArborXConfig.cmake.in
Labels: build

#708 Introduce GeometryTraits
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_GeometryTraits.hpp
  src/geometry/ArborX_Point.hpp
  src/geometry/ArborX_Sphere.hpp
  test/CMakeLists.txt
  test/tstBoostGeometryAdapters.cpp
  test/tstCompileOnlyGeometry.cpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#712 Template BruteForce on BoundingVolume
  src/ArborX_BruteForce.hpp
  test/CMakeLists.txt
Labels: API

#715 Require C++17 standard
  .clang-tidy
  .jenkins/continuous.groovy
  CMakeLists.txt
  examples/dbscan/CMakeLists.txt
  src/details/ArborX_DetailsTreeConstruction.hpp
Labels: build, testing, backward incompatible

#718 Switch static_assert with empty messages to single-argument versions
  .clang-tidy
  examples/dbscan/ArborX_DBSCANVerification.hpp
  examples/dbscan/dbscan.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtAccessibilityTraits.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
  test/ArborXTest_TreeTypeTraits.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/BoostTest_CUDA_clang_workarounds.hpp
  test/tstCompileOnlyWeightedEdges.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsTreeNodeLabeling.cpp
  test/tstMinimumSpanningTree.cpp
  test/tstRay.cpp
  test/tstScopedProfileRegion.cpp
Labels: refactoring

#714 Update SYCL testing
  docker/Dockerfile.sycl
Labels: testing

#701 Get rid of centroid() in favor of returnCentroid()
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: refactoring

#713 Introduce new multi-dimensional geometries
  src/geometry/ArborX_GeometryTraits.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_HyperPoint.hpp
  src/geometry/ArborX_HyperSphere.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#722 Generalize Morton code generation and provide it for dimensions 4-6
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_HyperPoint.hpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsMortonCodes.cpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement

#725 Move static_assert in geometry algorithms to launchers
  src/geometry/ArborX_DetailsAlgorithms.hpp
Labels: refactoring

#730 Use math function in Kokkos namespace for raytracing example if available
  examples/raytracing/example_raytracing.cpp
Labels: bug

#726 Make BVH work with multi-dimensional data
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_HyperBox.hpp
  test/tstCompileOnlyAccessTraits.cpp
  test/tstCompileOnlyCallbacks.cpp
  test/tstCompileOnlyTypeRequirements.cpp
Labels: enhancement
