Repository arborx/ArborX, pull requests merged in 2022-11, with the labels that each got.

#774 Fix `min` and `max` algorithms for element types other than `int`
  src/details/ArborX_DetailsUtils.hpp
  test/tstDetailsUtils.cpp
Labels: bug

#776 Get rid of toView duplicate function in the DBSCAN test
  test/tstDBSCAN.cpp
Labels: testing

#778 Fix CompileOnlyGeometry test
  test/tstCompileOnlyGeometry.cpp
Labels: bug

#777 Introduce dendrogram construction based on union-find
  src/details/ArborX_Dendrogram.hpp
  src/details/ArborX_DetailsDendrogram.hpp
  src/details/ArborX_DetailsWeightedEdge.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/CMakeLists.txt
  test/tstDendrogram.cpp
Labels: enhancement

#783 Add HDBSCAN
  benchmarks/dbscan/dbscan.cpp
  benchmarks/dbscan/dbscan_timpl.hpp
  src/ArborX_HDBSCAN.hpp
Labels: enhancement, clustering

#785 Prefer profiling regions to sections
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/dbscan/print_timers.cpp
  benchmarks/dbscan/print_timers.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_HDBSCAN.hpp
  src/details/ArborX_DetailsDendrogram.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: bug, refactoring

#787 Fix Style check in CI
  docker/Dockerfile.clang-format
  scripts/check_format_cpp.sh
  src/ArborX_DBSCAN.hpp
  test/tstDistributedTree.cpp
Labels: bug, testing

#786 Fix a bug when using distributed tree with rays
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  test/tstDistributedTree.cpp
Labels: bug
