Repository arborx/ArborX, pull requests merged in 2022-02, with the labels that each got.

#625 Revert "Remove __SYCL_DEVICE_ONLY__ guards for ptintf"
  examples/callback/example_callback.cpp
  examples/dbscan/ArborX_DBSCANVerification.hpp
Labels: bug

#624 Add facility to compute the minimum spanning tree
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsMutualReachabilityDistance.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyCallbacks.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstMinimumSpanningTree.cpp
Labels: enhancement, clustering

#631 Use lower bounds to avoid traversals in MST
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: performance

#633 Add 2D Morton codes
  src/details/ArborX_DetailsMortonCode.hpp
  test/CMakeLists.txt
  test/tstDetailsMortonCodes.cpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement

#638 Update GitLab CI
  .gitlab-ci.yml
Labels: testing

#635 Implement 64 bit Morton codes
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsMortonCodes.cpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement

#639 Prefer `Kokkos::[Experimental::]isfinite`
  src/details/ArborX_DetailsAlgorithms.hpp
  src/details/ArborX_DetailsKokkosExtMathFunctions.hpp
Labels: refactoring

#640 Fix a warning for 64-bit 2D Morton codes
  src/details/ArborX_DetailsMortonCode.hpp
Labels: build
