Repository arborx/ArborX, pull requests merged in 2022-03, with the labels that each got.

#642 Use specified execution space in view allocations
  examples/molecular_dynamics/example_molecular_dynamics.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: refactoring

#644 Move view helpers `ArborX:: -> KokkosExt::` and pass execution space instance
  examples/dbscan/dbscan.cpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsKokkosExtViewHelpers.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstDistributedTree.cpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeTraversalPolicy.cpp
Labels: refactoring

#637 Use 64-bit Morton indices by default in the BVH construction
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: performance

#647 Update arithmetic traits
  src/details/ArborX_Box.hpp
  src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp
  src/details/ArborX_KDOP.hpp
Labels: refactoring

#649 Remove unused node labeling utility
  src/details/ArborX_DetailsTreeNodeLabeling.hpp
Labels: refactoring

#636 Move computing offsets in a sorted view to general utilities and add a test
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsUtils.hpp
  test/tstDetailsUtils.cpp
Labels: refactoring

#646 Enable alternate projection onto space filling curve
  examples/viz/tree_visualization.cpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: enhancement

#653 Fix bugs in nearest search in DistributedTree
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedTree.cpp
Labels: bug

#655 Try specifying custom CI build directory for gitlab
  .gitlab-ci.yml
Labels: testing

#659 SYCL: Use device-code-split=per_kernel
  .jenkins/continuous.groovy
Labels: testing

#663 Add golden test comparing to mlpack for minimum spanning tree
  test/CMakeLists.txt
  test/mst_golden_test_edges.csv
  test/mst_golden_test_points.csv
  test/tstMinimumSpanningTreeGoldenTest.cpp
Labels: testing

#664 Set timeout on Jenkins CI builds
  .jenkins/continuous.groovy
Labels: testing

#617 Implementation of the water tight ray-triangle intersection
  src/details/ArborX_Ray.hpp
  src/details/ArborX_Triangle.hpp
  test/tstRay.cpp
Labels: enhancement

#665 Increase timeout in CI from 2h to 3h
  .jenkins/continuous.groovy
Labels: testing
