Repository arborx/ArborX, pull requests merged in 2022-07, with the labels that each got.

#696 Update DBSCAN README to include the command to run
  examples/dbscan/README.md
Labels: documentation

#698 Fix generation of the hollow sphere point cloud to be u.a.r.
  benchmarks/point_clouds/point_clouds.hpp
Labels: bug

#700 Add `distance` member function to nearest predicate
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_Predicates.hpp
Labels: refactoring

#704 Fix the expandBits() test
  test/tstDetailsMortonCodes.cpp
Labels: bug

#705 Remove deprecated version of BVH templated on a device type
  src/ArborX_LinearBVH.hpp
Labels: API

#706 Remove deprecated distributed tree stuff
  src/ArborX_DistributedSearchTree.hpp
  src/ArborX_DistributedTree.hpp
Labels: API

#707 Move geometry and KokkosExt related header files to separate directories
  CMakeLists.txt
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_KDOP.hpp
  src/geometry/ArborX_Point.hpp
  src/geometry/ArborX_Ray.hpp
  src/geometry/ArborX_Sphere.hpp
  src/geometry/ArborX_Triangle.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtAccessibilityTraits.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtArithmeticTraits.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMathFunctions.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMinMaxOperations.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtScopedProfileRegion.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSwap.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtVersion.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
Labels: build, refactoring
