Repository arborx/ArborX, pull requests merged in 2022-04, with the labels that each got.

#661 Improve MST performance by prefering lock-free atomics
  src/details/ArborX_MinimumSpanningTree.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyWeightedEdges.cpp
  test/tstMinimumSpanningTree.cpp
Labels: performance

#668 Fix some text in the DBSCAN README
  examples/dbscan/README.md
Labels: bug, documentation

#651 Update CHANGELOG
  CHANGELOG.md
Labels: documentation
