Repository arborx/ArborX, pull requests merged in 2022-09, with the labels that each got.

#734 Delegate hyper-geometries to old ones for pre Kokkos-3.7
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_HyperPoint.hpp
  src/geometry/ArborX_HyperSphere.hpp
  test/tstCompileOnlyTypeRequirements.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsMortonCodes.cpp
Labels: refactoring

#717 Generalize CartesianGrid for multiple dimensions and variable cell lengths
  examples/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsCartesianGrid.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMathFunctions.hpp
Labels: enhancement, refactoring

#731 Add brute force vs bvh benchmark to run multiple dimensions
  benchmarks/CMakeLists.txt
  benchmarks/brute_force_vs_bvh/CMakeLists.txt
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh.cpp
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh.hpp
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
Labels: enhancement

#736 Update DBSCAN runner to use multi-dimensional geometries and migrate it to benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  benchmarks/dbscan/CMakeLists.txt
  benchmarks/dbscan/README.md
  benchmarks/dbscan/converter.cpp
  benchmarks/dbscan/dbscan.cpp
  benchmarks/dbscan/dbscan.hpp
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/dbscan/input.txt
  examples/CMakeLists.txt
  examples/dbscan/CMakeLists.txt
  examples/dbscan/input.txt
  test/CMakeLists.txt
Labels: enhancement, refactoring

#747 Upgrade Kokkos to 3.7 in the SYCL build
  docker/Dockerfile.sycl
Labels: testing

#748 Require Kokkos 3.6
  .jenkins/continuous.groovy
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.hipcc
  src/kokkos_ext/ArborX_DetailsKokkosExtArithmeticTraits.hpp
Labels: build, testing

#545 Prefer Kokkos Tools hooks to hand rolled timers in DBSCAN
  benchmarks/dbscan/CMakeLists.txt
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/dbscan/print_timers.cpp
  benchmarks/dbscan/print_timers.hpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: refactoring

#742 Use shared radii during MST traversal only for Serial
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: performance

#753 Initialize core distances in MST to zero to be used in Max functor
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: bug
