Repository arborx/ArborX, pull requests merged in 2022-12, with the labels that each got.

#791 Fix return type in PermutedData with no attachment
  src/details/ArborX_DetailsPermutedData.hpp
Labels: performance

#793 Remove deprecated queryDispatch calls in the distributed tree
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
Labels: API

#796 Fix incorrect profiling region naming in CrsGraph
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
Labels: bug

#782 Add testing for union-find
  src/details/ArborX_DetailsUnionFind.hpp
  test/CMakeLists.txt
  test/tstUnionFind.cpp
Labels: testing

#797 Introduce KokkosExt::sortByKey
  src/details/ArborX_DetailsSortUtils.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
Labels: performance, refactoring

#794 Switch host in HIP testing from Serial to OpenMP
  docker/Dockerfile.hipcc
Labels: testing

#803 Do not bother with downloading GTest
  .gitlab-ci.yml
Labels: testing

#802 Add testing for MST with mutual reachability metric
  test/tstMinimumSpanningTreeGoldenTest.cpp
Labels: testing

#799 Require benchmark 1.5.4, update nightly containers to Ubuntu 22.04
  .gitlab-ci.yml
  .jenkins/nightly.groovy
  benchmarks/bvh_driver/CMakeLists.txt
  benchmarks/bvh_driver/benchmark_registration.hpp
  docker/Dockerfile.sycl
Labels: build, testing

#805 Annotate fences
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDendrogram.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
Labels: enhancement

#806 Move Google benchmark detection to the common CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/bvh_driver/CMakeLists.txt
Labels: build, benchmarks

#798 Cleanup `Details::dendrogramUnionFind()` and prefer `sortByKey()`
  src/details/ArborX_DetailsDendrogram.hpp
Labels: performance, refactoring
