Repository arborx/ArborX, pull requests merged in 2022-10, with the labels that each got.

#560 Warn about loss of precision in FDBSCAN-DenseBox
  src/details/ArborX_DetailsCartesianGrid.hpp
Labels: bug

#528 Add Gan-Tao cluster generator
  benchmarks/dbscan/data.hpp
  benchmarks/dbscan/dbscan.cpp
  benchmarks/dbscan/dbscan.hpp
  benchmarks/dbscan/dbscan_timpl.hpp
Labels: enhancement, clustering

#763 Add DBSCAN example
  examples/CMakeLists.txt
  examples/dbscan/CMakeLists.txt
  examples/dbscan/example_dbscan.cpp
Labels: enhancement

#764 Harmonize test and executables naming convention
  benchmarks/brute_force_vs_bvh/CMakeLists.txt
  benchmarks/bvh_driver/CMakeLists.txt
  benchmarks/dbscan/CMakeLists.txt
  benchmarks/dbscan/README.md
  benchmarks/distributed_tree_driver/CMakeLists.txt
  benchmarks/execution_space_instances/CMakeLists.txt
  examples/access_traits/CMakeLists.txt
  examples/brute_force/CMakeLists.txt
  examples/callback/CMakeLists.txt
  examples/molecular_dynamics/CMakeLists.txt
  examples/raytracing/CMakeLists.txt
  examples/simple_intersection/CMakeLists.txt
  examples/viz/CMakeLists.txt
  test/CMakeLists.txt
Labels: testing, refactoring, examples

#766 Fix gitlab
  .gitlab-ci.yml
Labels: testing

#762 Update CHANGELOG for release 1.3
  CHANGELOG.md
Labels: documentation

#772 Deduce point spatial dimension from view static extent
  src/details/ArborX_AccessTraits.hpp
  test/tstCompileOnlyAccessTraits.cpp
Labels: enhancement

#716 Convert point clouds to generate multi-dimensional data
  benchmarks/point_clouds/point_clouds.hpp
Labels: enhancement

#767 Add a faster implementation of the union-find for Serial
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsUnionFind.hpp
Labels: performance
