Repository arborx/ArborX, pull requests merged in 2022-01, with the labels that each got.

#608 Switch one CI build to test Kokkos 3.5.00
  .jenkins/continuous.groovy
Labels: testing

#598 Add nightly HIP build with the latest ROCm release
  .jenkins/nightly.groovy
Labels: testing

#609 Print Kokkos version during configuration
  CMakeLists.txt
Labels: build

#619 Fix Kokkos header includes
  examples/dbscan/ArborX_DBSCANVerification.hpp
  test/tstQueryTreeIntersectsKDOP.cpp
Labels: refactoring

#614 Update SYCL compiler and remove printf guarding with SYCL
  .jenkins/continuous.groovy
  docker/Dockerfile.sycl
  examples/callback/example_callback.cpp
  examples/dbscan/ArborX_DBSCANVerification.hpp
Labels: testing

#620 Cancel previous CI builds when changes are pushed to the branch
  .jenkins/continuous.groovy
Labels: testing
