Repository arborx/ArborX, pull requests merged in 2022-06, with the labels that each got.

#680 Bump Kokkos to 3.6 in gitlab
  .gitlab-ci.yml
Labels: testing

#594 Silence warnings from building SYCL image
  docker/Dockerfile.sycl
Labels: testing

#672 Use ropes for all backends
  src/ArborX_LinearBVH.hpp
Labels: performance

#693 Avoid `Kokkos::InitArguments` struct
  examples/viz/tree_visualization.cpp
Labels: refactoring
