Repository arborx/ArborX, pull requests merged in 2023-08, with the labels that each got.

#922 Disable tests in the nightly CUDA build
  .jenkins/nightly.groovy
Labels: testing

#923 Suppress -Wsycl-target warnings for SYCL CI
  .jenkins/continuous.groovy
Labels: testing

#929 Replace ARBORX_CLASS_LAMBDA with KOKKOS_CLASS_LAMBDA
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtClassLambda.hpp
  test/tstDistributedTree.cpp
  test/tstQueryTreeCallbacks.cpp
Labels: refactoring

#918 Allow different floating point types in hierarchy
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  test/tstCompileOnlyTypeRequirements.cpp
Labels: bug

#933 Fix compiling with cuda-12.2
  src/details/ArborX_DetailsDistributor.hpp
Labels: bug

#542 Add example for 2D triangle-point intersection
  examples/CMakeLists.txt
  examples/triangle_intersection/CMakeLists.txt
  examples/triangle_intersection/triangle_intersection.cpp
Labels: examples

#934 Add CUDA-12.2.0-MPI nightly build
  .jenkins/nightly.groovy
Labels: testing

#937 Decrease the amount of memory used ccache
  .jenkins/continuous.groovy
Labels: testing

#941 Move APIv1 converters into a separate legacy header
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_DetailsLegacy.hpp
  src/details/ArborX_IndexableGetter.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: refactoring
