Repository arborx/ArborX, pull requests merged in 2023-06, with the labels that each got.

#882 Move citation details
  CITATION.bib
  README.md
Labels: documentation

#884 Drop default constructor for the point hyper gerometry
  src/geometry/ArborX_HyperPoint.hpp
Labels: bug

#886 Cherry-pick #885 to master
  CMakeLists.txt
Labels: build

#888 Add KokkosExt::bit_cast
  src/details/ArborX_MinimumSpanningTree.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtBitManipulation.hpp
Labels: refactoring

#893 Use constexpr instead of SFINAE in InsertGenerator
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
Labels: refactoring

#898 Wipe out previous kokkos and benchmark installs in gitlab-ci
  .gitlab-ci.yml
Labels: testing

#897 Allow different volumes for leaf and internal nodes
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: performance

#892 Change BasicBoundingVolumeHierarchy template arguments
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyTypeRequirements.cpp
Labels: API
