Repository arborx/ArborX, pull requests merged in 2023-07, with the labels that each got.

#895 Require Kokkos 4.0
  .gitlab-ci.yml
  .jenkins/continuous.groovy
  CMakeLists.txt
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
  test/CMakeLists.txt
  test/tstUnionFind.cpp
Labels: build, testing

#909 Test with C++20 in HIP CI
  .jenkins/continuous.groovy
Labels: testing

#910 Test SYCL with Kokkos 4.1.00
  .jenkins/continuous.groovy
  docker/Dockerfile.sycl
Labels: testing

#900 Switch the signature for the pure callback
  src/ArborX_BruteForce.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsMutualReachabilityDistance.hpp
  test/tstCompileOnlyCallbacks.cpp
  test/tstCompileOnlyTypeRequirements.cpp
  test/tstDetailsMutualReachabilityDistance.cpp
  test/tstQueryTreeCallbacks.cpp
Labels: API

#913 Enable tests and examples on the nightlies
  .jenkins/nightly.groovy
Labels: testing

#894 Properly compute tree bounds with indexables
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: refactoring

#911 Add nightly C++23 build
  .jenkins/nightly.groovy
Labels: testing

#914 Change default BoundingVolume for BasicBVH to the right dimensionality
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: enhancement

#912 Allow rm -rf commands fail on Gitlab CI
  .gitlab-ci.yml
Labels: testing
