Repository arborx/ArborX, pull requests merged in 2023-10, with the labels that each got.

#954 Compact radial basis functions and generic polynomial basis / Utility for moving least squares
  src/interpolation/details/ArborX_InterpDetailsCompactRadialBasisFunction.hpp
  src/interpolation/details/ArborX_InterpDetailsPolynomialBasis.hpp
  test/ArborX_EnableViewComparison.hpp
  test/CMakeLists.txt
  test/tstInterpDetailsCRBF.cpp
  test/tstInterpDetailsPolyBasis.cpp
Labels: enhancement

#955 Fix Boruvka dendrogram generation
  src/details/ArborX_MinimumSpanningTree.hpp
  test/tstDendrogram.cpp
Labels: bug

#963 Split MinimumSpanningTree header to manage complexity
  src/details/ArborX_DetailsMinimumSpanningTree.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: refactoring
