Repository arborx/ArborX, pull requests merged in 2023-09, with the labels that each got.

#944 Add several algorithm routines for triangles
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_GeometryTraits.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#945 Fix bug argument counter must be passed by reference
  test/utf_main.cpp
Labels: bug, testing

#948 Get rid of hardcoded float in the geometry algorithms
  src/geometry/ArborX_DetailsAlgorithms.hpp
Labels: enhancement

#939 Switch to using invoke_result_t
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
Labels: refactoring

#917 Allow TreeTraversal to run individual queries in non-batch mode
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  test/CMakeLists.txt
  test/tstQueryTreeCallbackQueryPerThread.cpp
Labels: enhancement

#950 Pseudo-inverse of symmetric matrices using SVD / Utility for moving least squares
  .github/workflows/windows.yml
  .gitignore
  src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
  test/ArborX_EnableViewComparison.hpp
  test/CMakeLists.txt
  test/tstInterpDetailsSVD.cpp
Labels: enhancement
