Repository arborx/ArborX, pull requests merged in 2023-03, with the labels that each got.

#834 Require Kokkos 3.7
  .gitlab-ci.yml
  .jenkins/continuous.groovy
  CMakeLists.txt
  benchmarks/brute_force_vs_bvh/CMakeLists.txt
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh.cpp
  benchmarks/dbscan/CMakeLists.txt
  benchmarks/dbscan/dbscan.cpp
  docker/Dockerfile
  docker/Dockerfile.hipcc
  docker/README.md
  examples/raytracing/example_raytracing.cpp
  src/details/ArborX_AccessTraits.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_HyperPoint.hpp
  src/geometry/ArborX_HyperSphere.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMathFunctions.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
  test/tstCompileOnlyAccessTraits.cpp
  test/tstDetailsHalfTraversal.cpp
  test/tstDetailsMortonCodes.cpp
Labels: build

#836 Drop KokkosExt:: mathematical functions (use Kokkos:: instead)
  src/details/ArborX_DetailsCartesianGrid.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMathFunctions.hpp
Labels: refactoring

#740 Use KOKKOS_CLASS_LAMBDA via ARBORX_CLASS_LAMBDA
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtClassLambda.hpp
  test/tstDistributedTree.cpp
  test/tstQueryTreeCallbacks.cpp
Labels: refactoring

#833 Rename `create_layout_right_mirror_view{->_no_init}` which does not initialize
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsUtils.hpp
  test/tstDetailsDistributedTreeImpl.cpp
Labels: performance, refactoring

#828 Deprecate ARBORX_USE_CUDA_AWARE_MPI and replace it ARBORX_USE_GPU_AWARE_NPI
  .jenkins/continuous.groovy
  CMakeLists.txt
  cmake/ArborXSettings.cmake.in
  src/ArborX_Config.hpp.in
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
Labels: build, API

#765 Add a develop benchmark
  benchmarks/CMakeLists.txt
  benchmarks/develop/CMakeLists.txt
  benchmarks/develop/develop.cpp
Labels: benchmarks

#840 Delay getting correct leaf indices in nearest
  src/details/ArborX_DetailsTreeTraversal.hpp
Labels: performance

#841 Work around ROCm 5.2 ICE
  test/tstQueryTreeRay.cpp
Labels: bug

#843 Do not include the scoped profile test when using newer Kokkos
  test/CMakeLists.txt
Labels: bug

#848 Drop outdated comment in `expand<Box1, Box2>`
  src/geometry/ArborX_DetailsAlgorithms.hpp
Labels: refactoring
