Repository arborx/ArborX, pull requests merged in 2023-05, with the labels that each got.

#856 Make data file sampling portable
  benchmarks/dbscan/data.hpp
Labels: bug

#857 Fixup executable path when running tests
  benchmarks/brute_force_vs_bvh/CMakeLists.txt
  benchmarks/bvh_driver/CMakeLists.txt
  benchmarks/dbscan/CMakeLists.txt
  benchmarks/develop/CMakeLists.txt
  benchmarks/distributed_tree_driver/CMakeLists.txt
  benchmarks/execution_space_instances/CMakeLists.txt
  benchmarks/union_find/CMakeLists.txt
  examples/access_traits/CMakeLists.txt
  examples/brute_force/CMakeLists.txt
  examples/callback/CMakeLists.txt
  examples/dbscan/CMakeLists.txt
  examples/molecular_dynamics/CMakeLists.txt
  examples/raytracing/CMakeLists.txt
  examples/simple_intersection/CMakeLists.txt
  examples/viz/CMakeLists.txt
  test/CMakeLists.txt
Labels: build

#860 Separate leaf and internal nodes, use different node types
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  test/tstDetailsTreeConstruction.cpp
Labels: performance, refactoring

#863 Do not do CUDA_LAMBDA check for Kokkos 4.1+
  CMakeLists.txt
Labels: build

#865 Switch ranges for leaf and internal indices
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeNodeLabeling.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/tstDetailsTreeConstruction.cpp
  test/tstDetailsTreeNodeLabeling.cpp
Labels: refactoring

#837 Update SYCL docker container avoiding buiding the compiler
  .jenkins/continuous.groovy
  docker/Dockerfile.sycl
  test/tstMinimumSpanningTreeGoldenTest.cpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeRay.cpp
Labels: testing

#864 Separate HappyTreeFunctions for internal and leaf nodes
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: performance, refactoring

#875 Add 8-10 dimensional Morton codes
  src/details/ArborX_DetailsMortonCode.hpp
  test/tstDetailsMortonCodes.cpp
Labels: enhancement

#879 Remove Enable template parameter from BasicBoundingVolumeHierarchy and DistributedTree
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
Labels: API
