Repository arborx/ArborX, pull requests merged in 2023-11, with the labels that each got.

#968 Fixup examples naming convention
  examples/access_traits/CMakeLists.txt
  examples/triangle_intersection/CMakeLists.txt
Labels: testing

#965 APIv2: change signature of the 3-argument callback
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_BruteForce.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsLegacy.hpp
  test/ArborXTest_LegacyTree.hpp
  test/tstCompileOnlyCallbacks.cpp
Labels: enhancement, refactoring

#971 Remove workaround for getting Boost version in CMake
  test/CMakeLists.txt
Labels: build
