Repository arborx/ArborX, pull requests merged in 2023-01, with the labels that each got.

#808 Add specialized "half" tree traversal for spatial predicates
  src/details/ArborX_DetailsHalfTraversal.hpp
  test/CMakeLists.txt
  test/tstDetailsHalfTraversal.cpp
Labels: enhancement

#809 Implement expand half to full (neighbor list)
  src/details/ArborX_DetailsExpandHalfToFull.hpp
  test/CMakeLists.txt
  test/boost_ext/CompressedStorageComparison.hpp
  test/tstDetailsExpandHalfToFull.cpp
Labels: enhancement

#810 Use half traversal in FDBSCAN
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
Labels: performance

#811 Use `TeamPolicy` in `Details::expandHalfToFull` to improve performance
  src/details/ArborX_DetailsExpandHalfToFull.hpp
Labels: performance

#781 Add union-find benchmark
  benchmarks/CMakeLists.txt
  benchmarks/union_find/CMakeLists.txt
  benchmarks/union_find/union_find.cpp
Labels: benchmarks

#813 Take optional label argument in `KokkosExt::clone[WithoutInitializingNorCopying]`
  src/details/ArborX_DetailsExpandHalfToFull.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
Labels: enhancement

#812 Add new facility to find "half" or "full" neighbor lists
  src/details/ArborX_NeighborList.hpp
  test/CMakeLists.txt
  test/tstNeighborList.cpp
Labels: enhancement

#817 Do not use size_t for permutation indices in Node
  src/details/ArborX_DetailsNode.hpp
Labels: refactoring

#820 Update the container os for gitlab workflow to Ubuntu 22.04
  .github/workflows/gitlab-ci.yml
Labels: testing

#819 Introduce ArborX::PairIndexRank
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_PairIndexRank.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/Search_UnitTestHelpers.hpp
  test/boost_ext/ArborXPairIndexRankComparison.hpp
  test/tstDistributedTree.cpp
Labels: testing, API
