Repository arborx/ArborX, pull requests merged in 2023-12, with the labels that each got.

#967 Cut down on the number of AccessTraits
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsMutualReachabilityDistance.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/tstNeighborList.cpp
Labels: refactoring

#977 [ci skip] Update CHANGELOG for 1.5
  CHANGELOG.md
Labels: documentation

#973 Require Kokkos 4.1
  .github/workflows/windows.yml
  .gitlab-ci.yml
  .jenkins/continuous.groovy
  .jenkins/nightly.groovy
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.hipcc
  docker/Dockerfile.sycl
  docker/README.md
  src/ArborX_BruteForce.hpp
  src/ArborX_HDBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsMinimumSpanningTree.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtBitManipulation.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtScopedProfileRegion.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
  test/CMakeLists.txt
  test/tstScopedProfileRegion.cpp
Labels: build

#970 Unify old and new interfaces in a single class
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  examples/triangle_intersection/triangle_intersection.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsLegacy.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyTypeRequirements.cpp
  test/tstDetailsMutualReachabilityDistance.cpp
Labels: API

#987 Avoid some extra calculations in intersects(sphere, point)
  src/geometry/ArborX_DetailsAlgorithms.hpp
Labels: performance

#969 Introduce PairValueIndex and AttachIndices
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  examples/triangle_intersection/triangle_intersection.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/details/ArborX_DetailsLegacy.hpp
  src/details/ArborX_DetailsNode.hpp
  src/details/ArborX_IndexableGetter.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/details/ArborX_PairValueIndex.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  test/CMakeLists.txt
  test/tstDetailsMutualReachabilityDistance.cpp
  test/tstDetailsTreeConstruction.cpp
Labels: API, refactoring

#978 Cut down on the number of AccessTraits<Predicates, PredicatesTag>
  .jenkins/continuous.groovy
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsPermutedData.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
Labels: refactoring

#995 Fix missing tag within AttachIndices
  src/details/ArborX_PairValueIndex.hpp
Labels: bug

#986 Move KokkosExt namespace into Arborx::Details
  benchmarks/bvh_driver/bvh_driver.cpp
  benchmarks/dbscan/dbscan.cpp
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  benchmarks/point_clouds/point_clouds.hpp
  benchmarks/union_find/union_find.cpp
  examples/viz/tree_visualization.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Dendrogram.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/details/ArborX_NeighborList.hpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_KDOP.hpp
  src/geometry/ArborX_Ray.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  src/interpolation/details/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp
  src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtAccessibilityTraits.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtArithmeticTraits.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMinMaxOperations.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSwap.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtVersion.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/ArborX_BoostRangeAdapters.hpp
  test/ArborX_EnableViewComparison.hpp
  test/tstCompileOnlyWeightedEdges.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstDetailsKokkosExtViewHelpers.cpp
  test/tstDetailsMutualReachabilityDistance.cpp
  test/tstNeighborList.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeTraversalPolicy.cpp
  test/tstRay.cpp
Labels: refactoring

#1001 Modernize and fix callback detection
  src/details/ArborX_Callbacks.hpp
Labels: bug, refactoring

#1004 Drop `Details::AccessTraitsHelper`
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsLegacy.hpp
Labels: refactoring

#999 Deprecate exclusivePrefixSum, accumulate, adjacentDifference, iota and provide KokkosExt ones
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/union_find/union_find.cpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDendrogram.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsExpandHalfToFull.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/details/ArborX_NeighborList.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtStdAlgorithms.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/CMakeLists.txt
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstDetailsDistributedTreeImpl.cpp
  test/tstDetailsKokkosExtStdAlgorithms.cpp
  test/tstDetailsTreeConstruction.cpp
  test/tstDetailsUtils.cpp
  test/tstQueryTreeTraversalPolicy.cpp
  test/tstUnionFind.cpp
Labels: refactoring

#1002 Modernize space filling curve checks
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
Labels: refactoring

#998 Deprecate ArborX::{min,max,minMax} and move them to KokkosExt
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_Dendrogram.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMinMaxReduce.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp
  test/CMakeLists.txt
  test/tstDetailsKokkosExtMinMaxReduce.cpp
  test/tstDetailsUtils.cpp
  test/tstQueryTreeTraversalPolicy.cpp
Labels: refactoring

#1005 Remove ARBORX_TEST_QUERY_TREE_WITH_DISTANCE
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedTree.cpp
Labels: testing

#1000 Optimization for moving least squares
  src/interpolation/details/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp
  src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
Labels: performance

#993 Revert "Update Kokkos to 4.2 in the SYCL build"
  docker/Dockerfile.sycl
Labels: build

#996 Reorganize distributed tree files
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  test/tstDetailsDistributedTreeImpl.cpp
  test/tstDistributedTree.cpp
Labels: refactoring
