Repository arborx/ArborX, pull requests merged in 2024-09, with the labels that each got.

#1133 Update CHANGELOG for 1.7
  CHANGELOG.md
Labels: documentation

#1136 Add dependabot
  .github/dependabot.yml
Labels: security

#1138 Require Kokkos 4.3
  .jenkins/continuous.groovy
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.hipcc
Labels: build, testing, refactoring

#1139 Switch to using Kokkos::kokkos_swap post 4.3
  src/details/ArborX_DetailsMinimumSpanningTree.hpp
  src/geometry/ArborX_Ray.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtKernelStdAlgorithms.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSwap.hpp
Labels: refactoring

#1140 Switch to using Kokkos::{min,max} post 4.3
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  src/details/ArborX_DetailsMinimumSpanningTree.hpp
  src/details/ArborX_DetailsMortonCode.hpp
  src/details/ArborX_DetailsMutualReachabilityDistance.hpp
  src/details/ArborX_DetailsWeightedEdge.hpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_KDOP.hpp
  src/geometry/ArborX_Ray.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMinMaxOperations.hpp
Labels: refactoring

#906 Check that work is enqueued on the user-provided execution space instance
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/tstKokkosToolsExecutionSpaceInstances.cpp
Labels: testing

#1142 Add centroid for Tetrahedron
  src/geometry/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#1146 Switch spheres to new hyper-dimensional ones
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/execution_space_instances/execution_space_instances_driver.cpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/brute_force/example_brute_force.cpp
  examples/molecular_dynamics/example_molecular_dynamics.cpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
  src/details/ArborX_NeighborList.hpp
  src/details/ArborX_PredicateHelpers.hpp
  src/geometry/ArborX_HyperSphere.hpp
  src/geometry/ArborX_Ray.hpp
  src/geometry/ArborX_Sphere.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstCompileOnlyGeometry.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDistributedTreeSpatial.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstRay.cpp
Labels: backward incompatible

#1150 Add GeometryReducer and remove Box::operator+=
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  test/CMakeLists.txt
  test/tstDetailsGeometryReducer.cpp
  test/tstIndexableGetter.cpp
Labels: backward incompatible

#1148 Replace ArborX::Box with hyper-version
  examples/callback/example_callback.cpp
  examples/raytracing/example_raytracing.cpp
  examples/simple_intersection/example_intersection.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsCartesianGrid.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_HyperBox.hpp
  src/geometry/ArborX_KDOP.hpp
  src/geometry/ArborX_Ray.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  test/ArborX_BoostGeometryAdapters.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/CMakeLists.txt
  test/Search_UnitTestHelpers.hpp
  test/tstBoostGeometryAdapters.cpp
  test/tstCompileOnlyGeometry.cpp
  test/tstCompileOnlyTypeRequirements.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsGeometryReducer.cpp
  test/tstDetailsHalfTraversal.cpp
  test/tstDetailsTreeConstruction.cpp
  test/tstDistributedTreeSpatial.cpp
  test/tstIndexableGetter.cpp
  test/tstKDOP.cpp
  test/tstQueryTreeCallbackQueryPerThread.cpp
  test/tstQueryTreeCallbacks.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstQueryTreeDegenerate.cpp
  test/tstQueryTreeManufacturedSolution.cpp
  test/tstQueryTreeRay.cpp
  test/tstRay.cpp
Labels: backward incompatible

#1155 Remove APIv1 for BruteForce
  examples/brute_force/example_brute_force.cpp
  src/ArborX_BruteForce.hpp
  test/CMakeLists.txt
Labels: backward incompatible

#1154 Make hyper triangle default
  benchmarks/triangulated_surface_distance/generator.hpp
  benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp
  examples/triangle_intersection/triangle_intersection.cpp
  src/geometry/ArborX_Ray.hpp
  src/geometry/ArborX_Triangle.hpp
  test/tstDetailsAlgorithms.cpp
  test/tstRay.cpp
Labels: backward incompatible

#1156 Hide ArborX::PairIndexRank
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  examples/distributed_tree/distributed_knn.cpp
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_PairIndexRank.hpp
  test/ArborXTest_PairIndexRank.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedTreeNearest.cpp
  test/tstDistributedTreeSpatial.cpp
Labels: refactoring, backward incompatible

#1151 Remove deprecated code in ArborX_DetailsUtils.hpp
  src/details/ArborX_DetailsUtils.hpp
Labels: backward incompatible

#1157 Get rid of APIv1 in DistributedTree
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
  test/Search_UnitTestHelpers.hpp
  test/tstDistributedTreeNearest.cpp
  test/tstDistributedTreeSpatial.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
Labels: backward incompatible

#1147 Add convert() for geometries
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsDistributedTreeNearestHelpers.hpp
  src/details/ArborX_NeighborList.hpp
  src/details/ArborX_PredicateHelpers.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: refactoring

#1159 Switch examples and most benchmarks to APIv2
  benchmarks/execution_space_instances/execution_space_instances_driver.cpp
  benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/access_traits/example_host_access_traits.cpp
  examples/brute_force/example_brute_force.cpp
  examples/callback/example_callback.cpp
  examples/molecular_dynamics/example_molecular_dynamics.cpp
  examples/raytracing/example_raytracing.cpp
  examples/simple_intersection/example_intersection.cpp
  examples/triangle_intersection/triangle_intersection.cpp
  examples/viz/tree_visualization.cpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
Labels: examples, benchmarks

#1160 Switch bvh_driver benchmark to APIv2
  benchmarks/bvh_driver/benchmark_registration.hpp
  benchmarks/bvh_driver/bvh_driver.cpp
Labels: benchmarks

#1161 Get rid of APIv1 in BVH
  src/ArborX_BruteForce.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsLegacy.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_KDOP.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  test/ArborXTest_LegacyTree.hpp
  test/ArborXTest_TreeTypeTraits.hpp
  test/CMakeLists.txt
  test/tstDetailsHalfTraversal.cpp
  test/tstDetailsTreeConstruction.cpp
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsExecutionSpaceInstances.cpp
  test/tstNeighborList.cpp
  test/tstQueryTreeCallbackQueryPerThread.cpp
  test/tstQueryTreeIntersectsKDOP.cpp
  test/tstQueryTreeRay.cpp
  test/tstQueryTreeTraversalPolicy.cpp
Labels: backward incompatible

#1152 Switch to using Kokkos StdAlgorithms post 4.3
  src/kokkos_ext/ArborX_DetailsKokkosExtStdAlgorithms.hpp
  test/tstDetailsKokkosExtStdAlgorithms.cpp
Labels: refactoring

#1162 Increase minimum NVCC version requirement
  .jenkins/continuous.groovy
  CMakeLists.txt
  src/ArborX_DBSCAN.hpp
  test/ArborXTest_LegacyTree.hpp
Labels: testing, backward incompatible

#1163 Fix return type of getIndexable in HappyTreeFriends
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  test/tstIndexableGetter.cpp
Labels: bug, testing
