Repository arborx/ArborX, pull requests merged in 2024-11, with the labels that each got.

#1181 Move `DefaultIndexableGetter` to `Experimental::` and provide CTAD for `Indexables`
  src/cluster/ArborX_DBSCAN.hpp
  src/distributed/ArborX_DistributedTree.hpp
  src/spatial/ArborX_BruteForce.hpp
  src/spatial/ArborX_LinearBVH.hpp
  src/spatial/detail/ArborX_IndexableGetter.hpp
  test/CMakeLists.txt
  test/tstCompileOnlyTypeRequirements.cpp
  test/tstDetailsTreeConstruction.cpp
  test/tstIndexableGetter.cpp
Labels: refactoring

#1172 Remove PrimitivesTag and PredicatesTag
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/bvh_driver/benchmark_registration.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/access_traits/example_host_access_traits.cpp
  examples/brute_force/example_brute_force.cpp
  examples/callback/example_callback.cpp
  examples/molecular_dynamics/example_molecular_dynamics.cpp
  examples/raytracing/example_raytracing.cpp
  src/cluster/ArborX_DBSCAN.hpp
  src/cluster/ArborX_MinimumSpanningTree.hpp
  src/distributed/ArborX_DistributedTree.hpp
  src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  src/spatial/ArborX_BruteForce.hpp
  src/spatial/ArborX_LinearBVH.hpp
  src/spatial/detail/ArborX_AccessTraits.hpp
  src/spatial/detail/ArborX_AttachIndices.hpp
  src/spatial/detail/ArborX_Callbacks.hpp
  src/spatial/detail/ArborX_NeighborList.hpp
  src/spatial/detail/ArborX_PermutedData.hpp
  src/spatial/detail/ArborX_PredicateHelpers.hpp
  test/ArborXTest_LegacyTree.hpp
  test/ArborX_BoostRTreeHelpers.hpp
  test/tstAttachIndices.cpp
  test/tstCompileOnlyAccessTraits.cpp
  test/tstCompileOnlyCallbacks.cpp
  test/tstDBSCAN.cpp
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstIndexableGetter.cpp
  test/tstQueryTreeIntersectsKDOP.cpp
Labels: refactoring, backward incompatible

#1128 Reorganize SVD
  src/interpolation/detail/ArborX_InterpDetailsMovingLeastSquaresCoefficients.hpp
  src/misc/ArborX_SymmetricSVD.hpp
  test/CMakeLists.txt
  test/tstDetailsSVD.cpp
Labels: refactoring

#1192 Update jenkins url to cloud1
  docker/Dockerfile
  docker/Dockerfile.hipcc
  docker/Dockerfile.sycl
Labels: testing

#1190 Introduce ARBORX_VERSION
  CMakeLists.txt
  src/ArborX_Config.hpp.in
Labels: enhancement
