Repository arborx/ArborX, pull requests merged in 2024-01, with the labels that each got.

#1016 Switch template arg order for attach_indices
  src/details/ArborX_PairValueIndex.hpp
Labels: refactoring

#1015 Switch top tree in DistributedTree to new API and do some cleanup
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
Labels: refactoring

#1024 Generalize GetNeighborList for points
  src/details/ArborX_NeighborList.hpp
  test/tstNeighborList.cpp
Labels: performance

#1008 Simplify the simple intersection example
  examples/simple_intersection/example_intersection.cpp
Labels: examples

#1017 Refactor DistributedTree to support APIv2
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  src/details/ArborX_DetailsLegacy.hpp
Labels: API, refactoring

#1027 Fix label for AMD GPU in the CI
  .jenkins/continuous.groovy
  docker/Dockerfile.hipcc
  src/ArborX_BruteForce.hpp
  src/ArborX_LinearBVH.hpp
  test/tstInterpDetailsMLSCoefficients.cpp
  test/tstInterpMovingLeastSquares.cpp
Labels: testing

#1030 Remove min version requirement for rocThrust
  CMakeLists.txt
Labels: build

#1026 Fix clang-tidy warnings
  .clang-tidy
  .jenkins/continuous.groovy
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  benchmarks/distributed_tree_driver/distributed_tree_driver.cpp
  examples/raytracing/example_raytracing.cpp
  examples/triangle_intersection/triangle_intersection.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_DBSCAN.hpp
  src/ArborX_DistributedTree.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_AccessTraits.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsPriorityQueue.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsStack.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/details/ArborX_NeighborList.hpp
  src/details/ArborX_SpaceFillingCurves.hpp
  src/geometry/ArborX_GeometryTraits.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtStdAlgorithms.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtSwap.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtViewHelpers.hpp
  test/ArborX_BoostRangeAdapters.hpp
  test/ArborX_EnableViewComparison.hpp
  test/tstDetailsDistributedTreeImpl.cpp
  test/tstMinimumSpanningTreeGoldenTest.cpp
  test/tstSequenceContainers.cpp
Labels: testing
