Repository arborx/ArborX, pull requests merged in 2024-07, with the labels that each got.

#733 Add DistributedTree query only taking a callback
  src/ArborX_DistributedTree.hpp
  src/details/ArborX_DetailsDistributedTreeImpl.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  test/tstDistributedTreeSpatial.cpp
Labels: enhancement

#1120 SYCL CI: Manually build oneDPL
  .jenkins/continuous.groovy
  docker/Dockerfile.sycl
Labels: testing

#1123 Set policy CMP0167 to use FindBoost module
  CMakeLists.txt
Labels: build

#1124 Remove specifying Kokkos_ENABLE_DEPRECATED_CODE in SYCL build
  docker/Dockerfile.sycl
Labels: testing

#1117 Add Experimental::make_ordered_intersects
  src/details/ArborX_PredicateHelpers.hpp
  test/tstQueryTreeRay.cpp
Labels: testing, API
