Repository arborx/ArborX, pull requests merged in 2024-04, with the labels that each got.

#1048 Switch CI from MI100 to MI210
  .jenkins/continuous.groovy
  .jenkins/nightly.groovy
Labels: testing

#1050 Make sure that CUDA instances are destroyed prior to destroying streams
  benchmarks/execution_space_instances/execution_space_instances_driver.cpp
  examples/access_traits/example_cuda_access_traits.cpp
Labels: bug, testing, examples, benchmarks

#1053 Implement nearest query for BruteForce
  src/ArborX_BruteForce.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsNearestBufferProvider.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  test/CMakeLists.txt
  test/tstKokkosToolsAnnotations.cpp
  test/tstKokkosToolsDistributedAnnotations.cpp
Labels: enhancement

#1056 Fix 1.5.0 -> 1.5 in CHANGELOG
  CHANGELOG.md
Labels: documentation

#936 Update triangle example to API v2
  examples/CMakeLists.txt
  examples/triangle_intersection/CMakeLists.txt
  examples/triangle_intersection/triangle_intersection.cpp
Labels: examples

#1022 Switch HalfTraversal to APIv2
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_DetailsFDBSCAN.hpp
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_NeighborList.hpp
  test/tstDetailsHalfTraversal.cpp
Labels: performance, API, refactoring

#1052 Add triangulated surface distance benchmark
  benchmarks/CMakeLists.txt
  benchmarks/triangulated_surface_distance/CMakeLists.txt
  benchmarks/triangulated_surface_distance/triangulated_surface_distance.cpp
Labels: benchmarks

#1058 Improve distributed sorting of the results
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeSpatial.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  test/tstDetailsDistributedTreeImpl.cpp
Labels: performance

#1060 Revert MI100->MI210 for nightly testing
  .jenkins/nightly.groovy
Labels: testing

#1051 Simplify using APIv1 through APIv2 interface
  benchmarks/brute_force_vs_bvh/brute_force_vs_bvh_timpl.hpp
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  examples/simple_intersection/example_intersection.cpp
  src/ArborX_BruteForce.hpp
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_PairValueIndex.hpp
Labels: API

#1061 Update CHANGELOG for 1.6
  CHANGELOG.md
Labels: documentation

#1054 Require Kokkos 4.2
  .github/workflows/windows.yml
  .jenkins/continuous.groovy
  CMakeLists.txt
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  docker/Dockerfile.sycl
  examples/callback/example_callback.cpp
  examples/raytracing/example_raytracing.cpp
  src/details/ArborX_DetailsCartesianGrid.hpp
  src/details/ArborX_DetailsContainers.hpp
  src/details/ArborX_DetailsHappyTreeFriends.hpp
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_Ray.hpp
Labels: build

#1074 Move `OrderedSpatialPredicateTag` where it belongs that is namespace `Details::`
  src/ArborX_LinearBVH.hpp
  src/details/ArborX_Callbacks.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_Predicates.hpp
Labels: refactoring

#1059 Implement Box-Triangle intersection
  src/geometry/ArborX_DetailsAlgorithms.hpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#1072 Add nth_element function
  src/kokkos_ext/ArborX_DetailsKokkosExtKernelStdAlgorithms.hpp
  test/CMakeLists.txt
  test/tstDetailsKokkosExtKernelStdAlgorithms.cpp
Labels: enhancement
