Repository arborx/ArborX, pull requests merged in 2024-10, with the labels that each got.

#1145 Change Point, Box, Sphere CTAD
  examples/callback/example_callback.cpp
  src/geometry/ArborX_Box.hpp
  src/geometry/ArborX_Point.hpp
  src/geometry/ArborX_Sphere.hpp
  test/tstCompileOnlyGeometry.cpp
  test/tstIndexableGetter.cpp
  test/tstQueryTreeCallbackQueryPerThread.cpp
  test/tstQueryTreeComparisonWithBoost.cpp
  test/tstRay.cpp
Labels: backward incompatible

#1165 Add experimental Segment geometry
  src/geometry/ArborX_DetailsAlgorithms.hpp
  src/geometry/ArborX_GeometryTraits.hpp
  src/geometry/ArborX_Segment.hpp
  test/tstCompileOnlyGeometry.cpp
  test/tstDetailsAlgorithms.cpp
Labels: enhancement

#1164 Add CTAD for Triangle
  src/geometry/ArborX_Triangle.hpp
  test/tstCompileOnlyGeometry.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstRay.cpp
Labels: API

#1141 Leverage CTAD with [MD]RangePolicy
  benchmarks/dbscan/ArborX_DBSCANVerification.hpp
  benchmarks/dbscan/dbscan_timpl.hpp
  benchmarks/develop/develop.cpp
  benchmarks/execution_space_instances/execution_space_instances_driver.cpp
  benchmarks/triangulated_surface_distance/generator.hpp
  benchmarks/union_find/union_find.cpp
  benchmarks/utils/ArborXBenchmark_PointClouds.hpp
  examples/access_traits/example_cuda_access_traits.cpp
  examples/molecular_dynamics/example_molecular_dynamics.cpp
  examples/moving_least_squares/moving_least_squares.cpp
  examples/raytracing/example_raytracing.cpp
  examples/viz/tree_visualization.cpp
  src/ArborX_DBSCAN.hpp
  src/details/ArborX_Dendrogram.hpp
  src/details/ArborX_DetailsBatchedQueries.hpp
  src/details/ArborX_DetailsBruteForceImpl.hpp
  src/details/ArborX_DetailsCrsGraphWrapperImpl.hpp
  src/details/ArborX_DetailsDistributedTreeNearest.hpp
  src/details/ArborX_DetailsDistributedTreeUtils.hpp
  src/details/ArborX_DetailsDistributor.hpp
  src/details/ArborX_DetailsExpandHalfToFull.hpp
  src/details/ArborX_DetailsFDBSCANDenseBox.hpp
  src/details/ArborX_DetailsHalfTraversal.hpp
  src/details/ArborX_DetailsMinimumSpanningTree.hpp
  src/details/ArborX_DetailsNearestBufferProvider.hpp
  src/details/ArborX_DetailsSortUtils.hpp
  src/details/ArborX_DetailsTreeConstruction.hpp
  src/details/ArborX_DetailsTreeNodeLabeling.hpp
  src/details/ArborX_DetailsTreeTraversal.hpp
  src/details/ArborX_DetailsTreeVisualization.hpp
  src/details/ArborX_DetailsUtils.hpp
  src/details/ArborX_MinimumSpanningTree.hpp
  src/interpolation/ArborX_InterpMovingLeastSquares.hpp
  src/interpolation/details/ArborX_InterpDetailsSymmetricPseudoInverseSVD.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtMinMaxReduce.hpp
  src/kokkos_ext/ArborX_DetailsKokkosExtStdAlgorithms.hpp
  test/ArborXTest_Cloud.hpp
  test/tstDendrogram.cpp
  test/tstDetailsCrsGraphWrapperImpl.cpp
  test/tstDetailsHalfTraversal.cpp
  test/tstDetailsKokkosExtKernelStdAlgorithms.cpp
  test/tstDetailsKokkosExtUninitializedMemoryAlgorithms.cpp
  test/tstDetailsMutualReachabilityDistance.cpp
  test/tstIndexableGetter.cpp
  test/tstInterpDetailsCompactRadialBasisFunction.cpp
  test/tstInterpDetailsMLSCoefficients.cpp
  test/tstInterpMovingLeastSquares.cpp
  test/tstUnionFind.cpp
Labels: refactoring

#1169 Get rid of BOOST_TEST_DYN_LINK
  test/CMakeLists.txt
Labels: testing

#1174 cmake: make install path configurable
  CMakeLists.txt
Labels: build

#1173 Reorganize geometry/
  src/cluster/detail/ArborX_BoruvkaHelpers.hpp
  src/cluster/detail/ArborX_MutualReachabilityDistance.hpp
  src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp
  src/geometry/ArborX_KDOP.hpp
  src/geometry/ArborX_Ray.hpp
  src/geometry/ArborX_Segment.hpp
  src/geometry/ArborX_Tetrahedron.hpp
  src/geometry/algorithms/ArborX_Centroid.hpp
  src/geometry/algorithms/ArborX_Convert.hpp
  src/geometry/algorithms/ArborX_Distance.hpp
  src/geometry/algorithms/ArborX_Equals.hpp
  src/geometry/algorithms/ArborX_Expand.hpp
  src/geometry/algorithms/ArborX_Intersects.hpp
  src/geometry/algorithms/ArborX_Reducer.hpp
  src/geometry/algorithms/ArborX_TranslateAndScale.hpp
  src/geometry/algorithms/ArborX_Valid.hpp
  src/geometry/detail/ArborX_GeometryAlgorithms.hpp
  src/interpolation/detail/ArborX_InterpDetailsCompactRadialBasisFunction.hpp
  src/spatial/detail/ArborX_BatchedQueries.hpp
  src/spatial/detail/ArborX_BruteForceImpl.hpp
  src/spatial/detail/ArborX_PredicateHelpers.hpp
  src/spatial/detail/ArborX_Predicates.hpp
  src/spatial/detail/ArborX_SpaceFillingCurves.hpp
  src/spatial/detail/ArborX_TreeConstruction.hpp
  src/spatial/detail/ArborX_TreeTraversal.hpp
  test/ArborXTest_LegacyTree.hpp
  test/tstBoostGeometryAdapters.cpp
  test/tstBoostRangeAdapters.cpp
  test/tstDetailsAlgorithms.cpp
  test/tstDetailsGeometryReducer.cpp
  test/tstDetailsTreeConstruction.cpp
  test/tstInterpDetailsCompactRadialBasisFunction.cpp
  test/tstKDOP.cpp
Labels: refactoring

#1170 Add upper_bound kernel
  src/kokkos_ext/ArborX_KokkosExtKernelStdAlgorithms.hpp
  test/CMakeLists.txt
  test/tstDetailsKokkosExtKernelStdAlgorithms.cpp
Labels: enhancement

#1177 Update nightly CI gcc build
  .jenkins/nightly.groovy
Labels: testing

#1185 Removed unused argument in determineBufferLayout
  src/distributed/detail/ArborX_Distributor.hpp
Labels: refactoring
